spacing = 1
padding = 1

hide_ascii = false
prefer_small_ascii = true

separator = "󰧂"
#separator = ">"
separator_color = "6"
key_color = "4"

[custom_ascii]
color = "White"
path = "~/.config/macchina/themes/ascii-tmux"

[palette]
type = "Light"
visible = true

[box]
title = " fetch! "
border = "rounded"
visible = false 

[box.inner_margin]
x = 1
y = 0

[keys]
host = "Host"
kernel = "Kernel"
os = "OS"
wm = "WM"
terminal = "Term"
distro = "Distro"
shell = "Shell"
packages = "Packs"
uptime = "Online"
