spacing = 1
padding = 1

hide_ascii = false
prefer_small_ascii = true

separator = "󰧂"
#separator = ">"
separator_color = "green"
key_color = "red"

[custom_ascii]
color = "White"
path = "~/.config/macchina/themes/ascii-tmux"

[palette]
type = "Light"
visible = true
glyph = "  "

[box]
title = " fetch! "
border = "rounded"
visible = false

[box.inner_margin]
x = 1
y = 0

[keys]
host = " Host"
kernel = "󰌽 Kernel"
os = " OS"
de = " DE"
wm = " WM"
distro = " Distro"
terminal = " Term"
shell = " Shell"
packages = " Packs"
uptime = "󰥔 Online"
