decoration {
  blur {
    enabled = true
    size = 12
    passes = 2
    contrast = 2
    brightness = 0.5
    noise = 0.025
    ignore_opacity = true
    new_optimizations = true
    popups = true
    popups_ignorealpha = 0.9
    xray = true
  }
}
