plugin {
  borders-plus-plus {
    add_borders = 1 # 0 - 9

    # you can add up to 9 borders
    col.border_0 = rgb($borderAlpha)
    col.border_1 = rgb($shadowAlpha)

    # -1 means "default" as in the one defined in general:border_size
    border_size_0 = -1
    border_size_1 = 1

    # makes outer edges match rounding of the parent. Turn on / off to better understand. Default = on.
    natural_rounding = off
  }
}
