source=./moon-colors.conf

general {
  gaps_in = 2
  gaps_out = 4
  gaps_workspaces = 50

  border_size = 1
  col.inactive_border = rgba($bgAltAlphaFF)
  col.active_border = rgba($borderAlphaFF)
}

decoration {
  rounding_power = 2.4
  rounding = 6
  active_opacity = 0.95
  inactive_opacity = 0.95
  fullscreen_opacity = 0.95
  border_part_of_window = true

  blur {
    enabled = true
    size = 12
    passes = 3
    contrast = 2
    noise = 0.05
    brightness = 0.85
    ignore_opacity = true
    new_optimizations = true
    popups = true
    popups_ignorealpha = 0.9
    xray = true
  }

  shadow {
    enabled = false
    color = rgba(0F0F0F00)
  }
}

windowrule = match:class kitty, opaque true
windowrule = match:fullscreen 1, opaque true

layerrule = blur on, match:namespace waybar
layyerule = blur:brightness 2, match:namespace waybar
layerrule = ignore_alpha 0.9, match:namespace waybar

layerrule = blur on, match:namespace rofi
layerrule = ignore_alpha 0.9, match:namespace rofi
layyerule = match:namespace rofi, opacity 0.9 0.9 0.9
