source=./hyprland/vars.conf
source=./hyprland/exec.conf

source=./hyprland/general.conf
source=./hyprland/keybinds.conf

source=./hyprland/rules.conf
source=./hyprland/workspaces.conf

source=./hyprland/animations.conf
source=./hyprland/theming/theme.conf

source=./hyprland/plugins/borders-plus-plus.conf
source=./hyprland/plugins/hyprfocus.conf
#source=./hyprland/plugins/hyprspace.conf
source=./hyprland/plugins/hyprbars.conf
