source=./hyprland/theming/colors/moon.conf

$font = Inter

general {
  hide_cursor = false
  ignore_empty_input = true
  fail_timeout = 1000
}

animations {
  enabled = true
  bezier = linear, 1, 1, 0, 0
  animation = fadeIn, 1, 5, linear
  animation = fadeOut, 1, 5, linear
  animation = inputFieldDots, 1, 2, linear
}

background {
  monitor =
  path = $HOME/Pictures/Wallpapers/bridge.jpg
  blur_passes = 4
  blur_size = 1
  contrast = 1.3
  vibrancy = 0.2
  brightness = 0.6
}

input-field {
  monitor =
  size = 250, 35

  outline_thickness = 1
  outer_color = rgba($borderAlphaE1)
  check_color = $line
  fail_color = $diag_red
  inner_color = $bg

  font_color = $fg
  fade_on_empty = false
  rounding = 8

  font_family = $font
  placeholder_text = <i>Password...</i>
  fail_text = $PAMFAIL

  # uncomment to use a letter instead of a dot to indicate the typed password
  # dots_text_format = *
  dots_center = true
  dots_size = 0.2
  dots_spacing = 0.3

  # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
  #hide_input = true

  position = 0, 200
  halign = center
  valign = bottom
}

# User
label {
  monitor =
  text = $USER
  color = $fg
  font_size = 15
  font_family = Inter Medium

  position = -5, -165
  halign = center
  valign = center 
}

image {
  monitor =
  path = $HOME/Pictures/Wallpapers/haruko-pfp.png
  size = 125
  rounding = -1
  border_size = 1
  border_color = $fg

  position = 0, -80
  halign = center
  valign = center
  xray = true
}

label {
  monitor =
  text=󰌾
  font_size = 30

  position = 0, -25
  halign = center
  valign = top
}

# TIME
label {
  monitor =
  text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
  font_size = 50
  font_family = $font Bold

  position = 0, -80
  halign = center
  valign = top
}

# DATE
label {
  monitor = 
  text = cmd[update:60000] date +"%A, %B %d" # update every 60 seconds
  font_size = 15
  font_family = $font

  position = 0, -160
  halign = center
  valign = top
}
