## Lighting
exec-once = uwsm-app -- hyprsunset &
exec-once = uwsm-app -- nerdshade -longitude -123.113952 -latitude 49.260872 -loop &

# Wallpaper
exec-once = uwsm-app -- awww-daemon -f xrgb &

# Hyprland services
exec-once = uwsm-app -- /usr/lib/soteria-polkit/soteria &
exec-once = uwsm-app -- walker --gapplication-service &
exec-once = uwsm-app -- easyeffects --gapplication-service &

# Shell
exec-once = uwsm-app -- swaync &
exec-once = uwsm-app -- swayosd-server &
exec-once = uwsm-app -- waybar &
exec-once = uwsm-app -- nwg-dock-hyprland -d -i 32 -w 0 -c walker -hd 10 -mt 10 -mb 10 -f -a start -p right -lp start -o DP-1 -x &

# Reloads headers
exec = hyprpm reload

## Clipboard
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store
exec-once = uwsm-app -- wl-clip-persist --clipboard regular

# Userspace
exec-once = [workspace 1 silent] uwsm-app -- $terminal tmux &
exec-once = [workspace 2 silent] uwsm-app -- discord &
exec-once = [workspace 2 silent] uwsm-app -- spotify-launcher &
exec-once = [workspace special silent] uwsm-app -- $browser &
