# Hyprland services
exec-once = uwsm-app -- swaync
exec-once = uwsm-app -- swayosd-server
exec-once = uwsm-app -- /usr/lib/hyprpolkitagent/hyprpolkitagent

exec-once = uwsm-app -- swww-daemon -f xrgb

exec-once = uwsm-app -- elephant # Needed for walker
exec-once = uwsm-app -- walker --gapplication-service
exec-once = uwsm-app -- waybar

## Lighting
exec-once = uwsm-app -- hyprsunset
exec-once = uwsm-app -- nerdshade -longitude -123.113952 -latitude 49.260872 -loop
exec-once = uwsm-app -- wluma

## Cursor theme
# exec-once = hyprctl setcursor miniature 48

exec-once = hyprpm reload -n
exec = hyprctl dismissnotify

## Clipboard
exec-once = uwsm-app -- wl-paste --type text --watch cliphist store
exec-once = uwsm-app -- wl-paste --type image --watch cliphist store
exec-once = uwsm-app -- wl-clip-persist --clipboard regular

# Userspace
exec-once = [workspace 1 silent] uwsm-app -- kitty tmux
exec-once = [workspace 1 silent] uwsm-app -- zen-browser
# Disables animations for initial startup
# exec = sleep 1 && hyprctl keyword animations:enabled true

