bind = $mainMod, RETURN, exec, uwsm-app -- $terminal
bind = $mainMod SHIFT, S, movetoworkspace, special
bind = $mainMod, C, killactive

bind = $mainMod, M, exec, uwsm stop

bind = $mainMod, Z, fullscreen, 1
bind = $mainMod, F, fullscreen

bind = $mainMod, R, exec, uwsm-app -- $menu
bind = $mainMod, E, exec, uwsm-app -- $fileManager
bind = $mainMod, B, exec, pkill -x -SIGUSR1 waybar || uwsm-app -- waybar
bind = $mainMod SHIFT, B, exec, pkill -x -SIGUSR2 waybar || uwsm-app -- waybar

bind = $mainMod, T, togglesplit # dwindle

#bind = $mainMod, S, exec, bash -c hyprctl dispatch togglespecialworkspace

#opacity toggle
bind = $mainMod, O, exec, $SCRIPTDIR/kitty_opacity.sh

# Move focus with vim binds
bind = $mainMod, h, movefocus, l
bind = $mainMod, l, movefocus, r
bind = $mainMod, k, movefocus, u
bind = $mainMod, j, movefocus, d

# Resizing
binde = $mainMod, right, resizeactive, 20 0
binde = $mainMod, left, resizeactive, -20 0
binde = $mainMod, up, resizeactive, 0 -20
binde = $mainMod, down, resizeactive, 0 20

# Switch workspaces with mainMod + [0-4]
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4

# Move active window to a workspace with mainMod + SHIFT + [0-4]
bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4

# Example special workspace (scratchpad)
bind = $mainMod, S, togglespecialworkspace
bind = $mainMod SHIFT, S, movetoworkspace

# Run script to toggle mouse locking
bind = , F1, exec, $SCRIPTDIR/mouselock.sh
#bind = $mainMod, N,

bind = , XF86LaunchB, exec, uwsm-app -- $menu

# Brightness control
bindel = , XF86MonBrightnessUp, exec, uwsm-app -- swayosd-client --brightness +3 --device 'intel_backlight'
bindel = , XF86MonBrightnessDown, exec, uwsm-app -- swayosd-client --brightness -3 --device 'intel_backlight'

bindel = , XF86KbdBrightnessUp, exec, uwsm-app -- swayosd-client --brightness +3 --device 'smc::kbd_backlight'
bindel = , XF86KbdBrightnessDown, exec, uwsm-app -- swayosd-client --brightness -3 --device 'smc::kbd_backlight'

bindel = , XF86AudioRaiseVolume, exec, uwsm-app -- swayosd-client --output-volume raise
bindel = , XF86AudioLowerVolume, exec, uwsm-app -- swayosd-client --output-volume lower

bindl = , XF86AudioMute, exec, uwsm-app -- swayosd-client --output-volume mute-toggle

# Mouse Binds
bindm = SUPER, mouse:272, movewindow
bindm = SUPER, mouse:273, resizewindow
