layerrule {
  name = Modal

  match:modal = true

  ignore_alpha = 0.3
  blur = on
}
windowrule = float on, match:modal true

layerrule {
  name = Blur

  match:namespace = waybar|swaync-control-center|swaync-notification-window|swayosd|walker|hypr-dock|dock-popup|wleave

  ignore_alpha = 0.3
  blur_popups = on
  blur = on
  xray = on
}

layerrule {
  name = Dimming
  match:namespace = walker|swaync-control-center
  dim_around = off
}

layerrule {
  name = wleave
  match:namespace = wleave
  animation = fade 30%
  dim_around = on
}

layerrule {
  name = DisableAnim

  match:namespace = awww-daemon#|waybar
  no_anim = on
}

layerrule = animation slidefade top 5%, match:namespace swaync-control-center

windowrule = match:class game, workspace 2
windowrule = match:float true, xray off

layyerule = match:tag singleton_float, workspace special
windowrule = match:tag singleton_float, float on, size monitor_w/1.75 monitor_h/1.5
