workspace = 1, monitor:eDP-1, default:true
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = special:scratchpad, on-created-empty:$browser

layerrule = no_anim on, match:namespace swww-daemon
#layerrule = no_anim on, match:namespace waybar

layerrule = blur on, match:namespace waybar
layerrule = blur_popups on, match:namespace waybar
layerrule = ignore_alpha 0.9, match:namespace waybar
layerrule = xray on, match:namespace waybar

layerrule = blur on, match:namespace swaync-control-center
layerrule = blur_popups on, match:namespace swaync-control-center
layerrule = ignore_alpha 0.5, match:namespace swaync-control-center
layerrule = xray on, match:namespace swaync-control-center
layerrule = animation slidefade top 5%, match:namespace swaync-control-center

layerrule = blur on, match:namespace swaync-notification-window
layerrule = ignore_alpha 0.5, match:namespace swaync-notification-window
layerrule = xray on, match:namespace swaync-notification-window

layerrule = blur on, match:namespace swayosd
layerrule = blur_popups on, match:namespace swayosd
layerrule = ignore_alpha 0.3, match:namespace swayosd
layerrule = xray on, match:namespace swayosd

layerrule = blur on, match:namespace walker
layerrule = ignore_alpha 0.5, match:namespace walker
layerrule = xray on, match:namespace walker
layerrule = dim_around on, match:namespace walker

#workspace = w[tv1], gapsout:0, gapsin:0
#workspace = f[1], gapsout:0, gapsin:0
#windowrule = border_size 0, match:float 0, match:workspace w[tv1]
#windowrule = rounding 0, match:float 0, match:workspace w[tv1]
#windowrule = border_size 0, match:float 0, match:workspace f[1]
#windowrule = rounding 0, match:float 0, match:workspace f[1]

workspace = 1, gapsout:-1, gapsin:-1
windowrule = rounding 0, match:workspace 1
windowrule = border_size 1, match:workspace 1

windowrule = match:class org.quickshell, float on
windowrule = match:class game, workspace 2

#windowrule = match:fullscreen 1, opaque true
windowrule = match:class kitty, opaque true
