layerrule {
  name = Modal

  match:modal = true

  ignore_alpha = 0.3
  blur = on
}
windowrule = float on, match:modal true

layerrule {
  name = Blur

  match:namespace = waybar|swaync-control-center|swaync-notification-window|swayosd|walker|hypr-dock|dock-popup

  ignore_alpha = 0.3
  blur_popups = on
  blur = on
  xray = on
}

layerrule {
  name = Dimming
  match:namespace = walker|swaync-control-center
  dim_around = off
}

layerrule {
  name = DisableAnim

  match:namespace = awww-daemon#|waybar
  no_anim = on
}

layerrule = animation slidefade top 5%, match:namespace swaync-control-center


workspace = 9, gapsin:0
windowrule = match:workspace 9, match:class negative:zen, float on

#workspace = w[tv1], gapsout:0, gapsin:0
#workspace = f[1], gapsout:0, gapsin:0
#windowrule = border_size 0, match:float 0, match:workspace w[tv1]
#windowrule = rounding 0, match:float 0, match:workspace w[tv1]
#windowrule = border_size 0, match:float 0, match:workspace f[1]
#windowrule = rounding 0, match:float 0, match:workspace f[1]

#workspace = 1, gapsout:0, gapsin:0
#windowrule = rounding 0, match:float false, match:workspace 1
#windowrule = border_size 0, match:float false, match:workspace 1
#windowrule = rounding 0, match:float true, match:workspace f[1]
#windowrule = border_size 0, match:float true, match:workspace f[1]

windowrule = match:class org.quickshell, float on
windowrule = match:class game, workspace 2
windowrule = match:class discord, workspace 8
windowrule = match:class zen, workspace 9

windowrule = match:float true, xray off

layyerule = match:tag singleton_float, workspace special
windowrule = match:tag singleton_float, float on, size monitor_w/1.75 monitor_h/1.5

#windowrule = match:fullscreen 1, opaque true
#windowrule = match:class kitty, opaque true
