interface = "wlan0"
long_uptime = false
long_shell = true
long_kernel = false
current_shell = true
physical_cores = true
memory_percentage = true

theme = "theme"
show = [
  "Host",
  "Distribution",
  "WindowManager",
  "Terminal",
  "Packages",
  "Uptime"
]
