$bg = rgb(111111)
$bgAlpha = 111111

$bgAlt = rgb(1B1B1B)
$bgAltAlpha = 1B1B1B

$fg = rgb(A1A1AC)
$fgAlpha = A1A1AC

$shadow = rgb(0E0E0E)
$shadowAlpha = 0E0E0E

$border = rgb(303030)
$borderAlpha = 303030

$comment = rgb(4c4c57)
$commentAlpha = 4c4c57

$constant = rgb(b5b3a5)
$constantAlpha = b5b3a5

$func = rgb(6A6A7A)
$funcAlpha = 6A6A7A

$keyword = rgb(858599)
$keywordAlpha = 858599

$line = rgb(191919)
$lineAlpha = 191919

$number = rgb(ab836c)
$numberAlpha = ab836c

$operator = rgb(575D70)
$operatorAlpha = 575D70

$property = rgb(817882)
$propertyAlpha = 817882

$string = rgb(777d77)
$stringAlpha = 777d77

$type = rgb(6d748c)
$typeAlpha = 6d748c

$visual = rgb(242424)
$visualAlpha = 242424

$diag_red = rgb(DA7F7C)
$diag_redAlpha = DA7F7C

$diag_blue = rgb(869DDF)
$diag_blueAlpha = 869DDF

$diag_yellow = rgb(AF9974)
$diag_yellowAlpha = AF9974

$diag_green = rgb(69896F)
$diag_greenAlpha = 69896F
